apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: web-terminal-service
    app.kubernetes.io/managed-by: kustomize
  name: web-terminal-service
  namespace: {{ .Values.namespace }}
