apiVersion: v1
kind: Service
metadata:
  name: web-terminal-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
      protocol: TCP
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.ports.http.nodePort }}
      {{ end }}
      name: http
  selector:
    control-plane: web-terminal-service
